name: Main workflow

on: 
  push: 
    branches: 
     - main
     
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'liberica'
          java-version: '17'
          cache: 'gradle'
        run: java -version
      - run: ./gradlew build --no-daemon
    
      
    
  
  
