name: Main workflow

on: 
  workflow_dispatch:
    inputs:
        tag:
          description: 'Tag type'
          required: true
          default: 'patch'
          type: choice
          options:
          - major
          - minor
          - patch
  push: 
    branches: 
     - main
     
jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-22.04, ubuntu-20.04]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'liberica'
          java-version: '17'
      # - run: java -version
          # cache: 'gradle'
      # - run: ./gradlew clean build --no-daemon
      - uses: gradle/gradle-build-action@v2.8.0
        with:
          arguments: clean build
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.3
        with:
          name: jars ${{ matrix.os }}
          path: src/*/build/libs/*.jar

  release:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download jars
        uses: actions/download-artifact@v2.1.1
        with:
          # Artifact name
          name: jars ubuntu-22.04
          # path: # Destination path
      - name: Show jars
        run: |
          pwd
          find
