name: Main workflow

on: 
  push: 
    branches: 
     - main
     
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'liberica'
          java-version: '17'
          cache: 'gradle'
          run: java -version
      - run: ./gradlew clean build --no-daemon
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.3
        with:
          # Artifact name
          name: artifacts
          # A file, directory or wildcard pattern that describes what to upload
          path: src/*/build/libs/*.jar
      
    
  
  
